version: "3.9"

services:
  front:
    image: sermalenk/skypro-front:lesson-34
    ports:
      - 8000:80
    depends_on:
      - api
  api:
    image: igorek86/pusik2:version-1
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_healthy
    volumes:
      - ./.docker_env:/code/default_env
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  migrations:
    image: igorek86/pusik2:version-1
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./.docker_env:/code/default_env
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    command: python manage.py migrate
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-data:/var/lib/postgresql/data