version: "3.9"

services:
  front:
    image: sermalenk/skypro-front:lesson-36
    ports:
      - "8000:80"
    depends_on:
      - api
  api:
    build:
      context: .
    env_file: .env
    environment:
      DB_HOST: postgres2
    depends_on:
      postgres2:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  migrations:
    build:
      context: .
    env_file: .env
    environment:
      DB_HOST: postgres2
    depends_on:
      postgres2:
        condition: service_healthy
    command: python manage.py migrate

  postgres2:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 10s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
