version: "3.9"

services:
  front:
    image: sermalenk/skypro-front:lesson-34
    ports:
      - 8000:80
    depends_on:
      - api
  api:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_healthy
    volumes:
      - ./.docker_env:/code/default_env
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  migrations:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./.docker_env:/code/default_env
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 30s
      timeout: 5s
      retries: 5
    command: ["sh", "-c", "sleep 5 && python manage.py migrate"]
  postgres:
    image: postgres:latest
    environment:
      PASSWORD: postgres
      NAME: postgres
      USER: postgres
      HOST: localhost
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data