# Generated by Django 4.2.3 on 2023-07-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_category_comment_goal_delete_goalcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
