# Generated by Django 4.2.2 on 2023-09-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True, verbose_name='Chat ID')),
                ('verification_code', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('state', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
